name: Publish to Cargo

on:
  push:
    branches: [main]

jobs:
  publish:
    runs-on: ubuntu-latest

    name: "publish"

    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 0

      - name: Run publish-action
        uses: tu6ge/publish-action@v0.4.5
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
